GROQ_API_KEY = "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"

ADMIN_EMAIL = "matteogandino.ita@gmail.com"

ADMIN_PASSWORD = "1234"

GEMINI_API_KEY = "AIzaSyBnbizuXo9A8SjQetIt6kmoGm1xE5MZmy0"